[project]
name = "pyrocketcraft"
version = "1"

dependencies = [
    "numpy==1.24.3",
    "scipy>=1.5.2",
    "gym>=0.26.2",
    "pybullet==3.2.6",
    "torch>=2.1.2",
    "stable-baselines3[extra]==2.2.1",
]

[tool.setuptools]
packages = ["src"]
